import { type FormEvent, useEffect, useState } from 'react'
import { PlanPanel, StoreLimitNote } from '../components/Billing'
import { Button } from '../components/Button'
import { ManagersSection } from '../components/ManagersSection'
import { RequirementsEditor } from '../components/RequirementsEditor'
import { ResponsibilitiesEditor } from '../components/ResponsibilitiesEditor'
import { SpecialHoursEditor } from '../components/SpecialHoursEditor'
import { StoreInviteLink } from '../components/StoreInviteLink'
import { api } from '../lib/api'
import { useAuth } from '../lib/auth'
import { useConfirm } from '../lib/confirm'
import { useStore } from '../lib/store-context'
import { useT } from '../lib/i18n'
import type { BillingSummary, DayOfWeek, EmployeeStore, PayPeriodType, ShiftRequirement, Store } from '../types'

// every field but name is optional: the server leaves anything omitted as-is
type StorePatch = {
  name: string
  requiresOpenerSkill?: boolean
  pairNewWorkers?: boolean
  tracksClosingDuties?: boolean
  openTime?: string | null
  closeTime?: string | null
  nightStart?: string | null
  availabilityReminderDay?: DayOfWeek
  availabilityReminderTime?: string
  autoGenerateDay?: DayOfWeek
  autoGenerateTime?: string
}

const DAYS: DayOfWeek[] = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']

const to12 = (hhmm: string) => {
  const [h, m] = hhmm.split(':').map(Number)
  const ap = h < 12 ? 'AM' : 'PM'
  const h12 = h % 12 === 0 ? 12 : h % 12
  return `${h12}:${String(m).padStart(2, '0')} ${ap}`
}

// every half hour, "00:00".."23:30" — a plain <select> of these renders the
// same everywhere, unlike a native <input type="time">, which looks and
// behaves differently per browser/OS (and inconsistently blank/greyed-out
// until a value's actually picked)
const TIME_OPTIONS: string[] = Array.from({ length: 48 }, (_, i) => {
  const h = Math.floor(i / 2)
  const m = i % 2 === 0 ? '00' : '30'
  return `${String(h).padStart(2, '0')}:${m}`
})

export function Stores() {
  const t = useT()
  const confirm = useConfirm()
  const { user } = useAuth()
  const isOwner = user?.role === 'OWNER'
  const [stores, setStores] = useState<Store[]>([])
  const [links, setLinks] = useState<EmployeeStore[]>([])
  const [reqs, setReqs] = useState<ShiftRequirement[]>([])
  const [error, setError] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState<number | null>(null)
  const [showNeeds, setShowNeeds] = useState<number | null>(null)
  const [showHours, setShowHours] = useState<number | null>(null)
  const [showInvite, setShowInvite] = useState<number | null>(null)
  const [showResp, setShowResp] = useState<number | null>(null)
  const [showTiming, setShowTiming] = useState<number | null>(null)
  const [addingSectionFor, setAddingSectionFor] = useState<number | null>(null)
  const [org, setOrg] = useState<{
    id: number
    name: string
    payPeriodType: PayPeriodType
    payPeriodAnchor: string
    storeLimit: number | null
  } | null>(null)

  const [billing, setBilling] = useState<BillingSummary | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  useEffect(() => {
    if (!isOwner) return
    api.getOrg().then(setOrg).catch(() => {})
    api.getBilling().then(setBilling).catch(() => {})
  }, [isOwner])

  // back from Stripe Checkout: the plan arrives a moment later (Stripe tells
  // the server by webhook), so check again for a little while
  useEffect(() => {
    if (!isOwner || new URLSearchParams(window.location.search).get('billing') !== 'done') return
    let tries = 0
    const id = window.setInterval(() => {
      tries++
      api
        .getBilling()
        .then((b) => {
          setBilling(b)
          if (b.state === 'active' || tries >= 10) window.clearInterval(id)
        })
        .catch(() => {})
    }, 3000)
    return () => window.clearInterval(id)
  }, [isOwner])
  const atStoreLimit =
    billing?.storeLimit != null && stores.filter((s) => s.parentStoreId === null).length >= billing.storeLimit

  const { refreshStores } = useStore()
  function refresh() {
    // the header's store picker too, so an added or deleted store shows up there
    void refreshStores()
    return Promise.all([api.getStores(), api.getEmployeeStores(), api.getShiftRequirements()])
      .then(([s, l, r]) => {
        setStores(s)
        setLinks(l)
        setReqs(r)
      })
      .catch((e) => setError(e instanceof Error ? e.message : t('stores.errLoad')))
  }

  useEffect(() => {
    refresh().finally(() => setLoading(false))
  }, [])

  const workerCount = (storeId: number) => links.filter((l) => l.storeId === storeId).length
  const reqCount = (storeId: number) => reqs.filter((r) => r.storeId === storeId).length
  const sectionsOf = (storeId: number) => stores.filter((s) => s.parentStoreId === storeId)

  async function act(fn: () => Promise<unknown>) {
    setError(null)
    try {
      await fn()
      setEditing(null)
      await refresh()
    } catch (e) {
      setError(e instanceof Error ? e.message : t('stores.errGeneric'))
    }
  }

  async function addSection(parent: Store, name: string) {
    // first section under a store that already has its own shift requirements —
    // those requirements stay right where they are, but the store itself stops
    // being schedulable once it has sections, so make sure that's not a surprise
    if (
      sectionsOf(parent.id).length === 0 &&
      reqCount(parent.id) > 0 &&
      !(await confirm(t('stores.confirmFirstSection', { name: parent.name }), { tone: 'danger' }))
    ) {
      return
    }
    setError(null)
    try {
      await api.createStore({ name, requiresOpenerSkill: true, pairNewWorkers: false, parentStoreId: parent.id })
      setAddingSectionFor(null)
      await refresh()
    } catch (e) {
      setError(e instanceof Error ? e.message : t('stores.errGeneric'))
    }
  }

  return (
    <div className="mx-auto w-full max-w-2xl flex-1 p-4 pb-[calc(4rem+env(safe-area-inset-bottom))] sm:p-6">
      <h1 className="font-heading text-lg font-bold text-ink">{t('nav.mgr.stores')}</h1>
      {error && <p className="mt-2 font-body text-xs font-bold text-coral-dark">{error}</p>}

      {isOwner && org && (
        <>
          <SectionHeading title={t('settings.company')} />
          <div className="flex flex-col gap-2 rounded-2xl border-[2.5px] border-ink bg-paper p-3 shadow-[3px_3px_0_var(--color-ink)]">
            <OrgNameEditor org={org} onSaved={(o) => setOrg((prev) => prev && { ...prev, ...o })} />
            <PayCycleEditor org={org} onSaved={(o) => setOrg((prev) => prev && { ...prev, ...o })} />
          </div>
        </>
      )}

      {isOwner && billing && (
        <>
          <SectionHeading title={t('billing.heading')} />
          <PlanPanel billing={billing} onChange={setBilling} />
        </>
      )}

      <SectionHeading title={t('settings.locations')} hint={t('stores.subtitle')} />
      {isOwner &&
        billing &&
        // every store the plan pays for is in use (sections don't count) — the backend refuses too
        (atStoreLimit ? (
          <StoreLimitNote
            billing={billing}
            onAdded={(b) => {
              setBilling(b)
              setAddOpen(true)
            }}
          />
        ) : (
          <AddStore
            key={addOpen ? 'open' : 'closed'}
            startOpen={addOpen}
            onAdd={(patch) => {
              setAddOpen(false)
              void act(() => api.createStore(patch))
            }}
          />
        ))}

      {loading ? (
        <p className="mt-3 font-body text-sm text-muted-ink">{t('common.loading')}</p>
      ) : (
        <div className="flex flex-col gap-3">
          {stores
            .filter((s) => s.parentStoreId === null)
            .map((s) => (
              <div key={s.id} className="flex flex-col gap-2.5">
                {editing === s.id ? (
                  <EditStore
                    store={s}
                    hasSections={sectionsOf(s.id).length > 0}
                    onSave={(patch) => act(() => api.updateStore(s.id, patch))}
                    onCancel={() => setEditing(null)}
                  />
                ) : (
                  <StoreCard
                    store={s}
                    isOwner={isOwner}
                    hasSections={sectionsOf(s.id).length > 0}
                    workerCount={workerCount(s.id)}
                    reqCount={reqCount(s.id)}
                    showNeeds={showNeeds === s.id}
                    showHours={showHours === s.id}
                    showInvite={showInvite === s.id}
                    showResp={showResp === s.id}
                    onToggleNeeds={() => setShowNeeds((v) => (v === s.id ? null : s.id))}
                    onToggleHours={() => setShowHours((v) => (v === s.id ? null : s.id))}
                    onToggleInvite={() => setShowInvite((v) => (v === s.id ? null : s.id))}
                    onToggleResp={() => setShowResp((v) => (v === s.id ? null : s.id))}
                    showTiming={showTiming === s.id}
                    onToggleTiming={() => setShowTiming((v) => (v === s.id ? null : s.id))}
                    onSaveTiming={(patch) =>
                      void act(() => api.updateStore(s.id, patch)).then(() => setShowTiming(null))
                    }
                    onEdit={() => setEditing(s.id)}
                    onDelete={() => {
                      void confirm(t('stores.confirmDelete', { name: s.name }), {
                        tone: 'danger',
                        confirmLabel: t('stores.delete'),
                      }).then((ok) => {
                        if (ok) void act(() => api.deleteStore(s.id))
                      })
                    }}
                    onRefresh={refresh}
                  />
                )}

                {sectionsOf(s.id).map((sec) => (
                  <div key={sec.id} className="ml-4 flex flex-col gap-2.5 border-l-2 border-ink/15 pl-3 sm:ml-6">
                    {editing === sec.id ? (
                      <EditStore
                        store={sec}
                        onSave={(patch) => act(() => api.updateStore(sec.id, patch))}
                        onCancel={() => setEditing(null)}
                      />
                    ) : (
                      <StoreCard
                        store={sec}
                        isSection
                        isOwner={isOwner}
                        workerCount={workerCount(sec.id)}
                        reqCount={reqCount(sec.id)}
                        showNeeds={showNeeds === sec.id}
                        showHours={showHours === sec.id}
                        showInvite={showInvite === sec.id}
                        showResp={showResp === sec.id}
                        onToggleNeeds={() => setShowNeeds((v) => (v === sec.id ? null : sec.id))}
                        onToggleHours={() => setShowHours((v) => (v === sec.id ? null : sec.id))}
                        onToggleInvite={() => setShowInvite((v) => (v === sec.id ? null : sec.id))}
                        onToggleResp={() => setShowResp((v) => (v === sec.id ? null : sec.id))}
                        onEdit={() => setEditing(sec.id)}
                        onDelete={() => {
                          void confirm(t('stores.confirmDelete', { name: sec.name }), {
                            tone: 'danger',
                            confirmLabel: t('stores.delete'),
                          }).then((ok) => {
                            if (ok) void act(() => api.deleteStore(sec.id))
                          })
                        }}
                        onRefresh={refresh}
                      />
                    )}
                  </div>
                ))}

                {/* any manager of this store can add a section to it, not just an
                    owner — the page's own store list is already scoped to
                    stores this account manages, so every card here qualifies */}
                {addingSectionFor === s.id ? (
                  <div className="ml-4 sm:ml-6">
                    <AddSection onAdd={(name) => void addSection(s, name)} onCancel={() => setAddingSectionFor(null)} />
                  </div>
                ) : (
                  <button
                    onClick={() => setAddingSectionFor(s.id)}
                    className="ml-4 self-start rounded-full border-2 border-dashed border-ink/40 px-2.5 py-0.5 font-heading text-[11px] font-bold text-muted-ink sm:ml-6"
                  >
                    {t('stores.addSection')}
                  </button>
                )}
              </div>
            ))}
        </div>
      )}

      {isOwner && !loading && stores.length > 0 && (
        <div className="mt-6">
          <ManagersSection stores={stores} />
        </div>
      )}
    </div>
  )
}

function SectionHeading({ title, hint }: { title: string; hint?: string }) {
  return (
    <div className="mb-2 mt-6">
      <h2 className="font-body text-[11px] font-bold uppercase tracking-wide text-muted-ink">{title}</h2>
      {hint && <p className="font-body text-xs text-muted-ink">{hint}</p>}
    </div>
  )
}

function StoreCard({
  store: s,
  isSection = false,
  hasSections = false,
  isOwner,
  workerCount,
  reqCount,
  showNeeds,
  showHours,
  showInvite,
  showResp,
  showTiming = false,
  onToggleNeeds,
  onToggleHours,
  onToggleInvite,
  onToggleResp,
  onToggleTiming,
  onSaveTiming,
  onEdit,
  onDelete,
  onRefresh,
}: {
  store: Store
  showTiming?: boolean
  onToggleTiming?: () => void
  onSaveTiming?: (patch: StorePatch) => void
  isSection?: boolean
  /** true once this store has its own sections — it's no longer itself
   * schedulable, so its own "shift needs" would never actually be used */
  hasSections?: boolean
  isOwner: boolean
  workerCount: number
  reqCount: number
  showNeeds: boolean
  showHours: boolean
  showInvite: boolean
  showResp: boolean
  onToggleNeeds: () => void
  onToggleHours: () => void
  onToggleInvite: () => void
  onToggleResp: () => void
  onEdit: () => void
  onDelete: () => void
  onRefresh: () => void
}) {
  const t = useT()
  return (
    <div className="rounded-2xl border-[2.5px] border-ink bg-paper p-3 shadow-[3px_3px_0_var(--color-ink)]">
      <div className="flex flex-wrap items-start gap-x-3 gap-y-1.5">
        <div className="min-w-0 flex-1">
          <span className="font-heading text-sm font-bold text-ink">{s.name}</span>
          {isSection && (
            <span className="ml-1.5 rounded-full border border-ink/25 px-1.5 py-px font-body text-[9px] font-bold uppercase tracking-wide text-muted-ink">
              {t('stores.section.badge')}
            </span>
          )}
          <span className="mt-0.5 block font-body text-[11px] text-muted-ink">
            {/* once a store has sections, it's never itself scheduled, so its
                own worker count / opener / pairing / closing-duties settings
                never actually apply — only the shared hours are still real */}
            {!hasSections && (
              <>
                {workerCount === 1 ? t('stores.workerCount.one', { n: workerCount }) : t('stores.workerCount', { n: workerCount })}
                {' · '}
                {s.requiresOpenerSkill ? t('stores.openerRequired') : t('stores.anyoneCanOpen')}
                {s.pairNewWorkers && ` · ${t('stores.newWorkersPaired')}`}
                {!s.tracksClosingDuties && ` · ${t('stores.noClosingDuties')}`}
              </>
            )}
            {s.openTime && s.closeTime && (
              <>
                {!hasSections && ' · '}
                {to12(s.openTime)}–{to12(s.closeTime)}
                {s.nightStart && `, ${t('stores.nightFrom', { time: to12(s.nightStart) })}`}
              </>
            )}
          </span>
        </div>
        <div className="flex min-w-0 flex-wrap items-center gap-1.5">
          {/* once a store has sections, it's never itself scheduled again —
              its own "shift needs" would just sit there unused, so hide the
              button rather than invite setting up something pointless */}
          {hasSections ? (
            <span className="font-body text-[10px] text-muted-ink">{t('stores.needsLiveInSections')}</span>
          ) : (
            <button
              onClick={onToggleNeeds}
              className={`rounded-full border-2 border-ink px-2.5 py-0.5 font-heading text-[11px] font-bold ${
                reqCount === 0 ? 'bg-coral-bg text-coral-dark' : 'bg-cream text-ink'
              }`}
            >
              {t('stores.shiftNeeds', { n: reqCount })}
            </button>
          )}
          {/* hours are the physical location's hours (FOH/BOH open and close
              together) — set once on the main store, not per section */}
          {!isSection && (
            <button onClick={onToggleHours} className="rounded-full border-2 border-ink bg-cream px-2.5 py-0.5 font-heading text-[11px] font-bold text-ink">
              {t('stores.specialHoursBtn')}
            </button>
          )}
          {/* the parent's own sign-up link now covers every section (the
              worker picks which one to join), so a section doesn't need its
              own separate link */}
          {!isSection && (
            <button onClick={onToggleInvite} className="rounded-full border-2 border-ink bg-cream px-2.5 py-0.5 font-heading text-[11px] font-bold text-ink">
              {t('stores.signupLink')}
            </button>
          )}
          {/* when the weekly availability email and next-week auto-draft go
              out — a physical-location setting, like hours */}
          {!isSection && onToggleTiming && (
            <button onClick={onToggleTiming} className="rounded-full border-2 border-ink bg-cream px-2.5 py-0.5 font-heading text-[11px] font-bold text-ink">
              {t('stores.timing.button')}
            </button>
          )}
          {/* once a store has sections, closing-time roles are each
              section's own thing (FOH vs. BOH close differently) — set them
              up there instead */}
          {!hasSections && (
            <button onClick={onToggleResp} className="rounded-full border-2 border-ink bg-cream px-2.5 py-0.5 font-heading text-[11px] font-bold text-ink">
              {t('stores.responsibilitiesBtn')}
            </button>
          )}
          <button onClick={onEdit} className="rounded-full border-2 border-ink bg-cream px-2.5 py-0.5 font-heading text-[11px] font-bold text-ink">
            {t('stores.edit')}
          </button>
          {/* deleting a top-level store is owner-only (bigger, more structural),
              but a section can be removed by whoever manages it — same split
              as adding one; every card here already belongs to a store this
              account manages, so isSection alone is enough to allow it */}
          {(isOwner || isSection) && (
            <button onClick={onDelete} className="rounded-full border-2 border-coral px-2.5 py-0.5 font-heading text-[11px] font-bold text-coral-dark">
              {t('stores.delete')}
            </button>
          )}
        </div>
      </div>
      {showNeeds && !hasSections && <RequirementsEditor storeId={s.id} onChange={onRefresh} />}
      {showHours && !isSection && <SpecialHoursEditor storeId={s.id} />}
      {showInvite && !isSection && <StoreInviteLink storeId={s.id} />}
      {showTiming && !isSection && onSaveTiming && <TimingPanel store={s} onSave={onSaveTiming} />}
      {showResp && !hasSections && <ResponsibilitiesEditor storeId={s.id} />}
    </div>
  )
}

/** When this store emails workers to check next week's availability, and when
 * it auto-drafts next week — its own panel rather than buried in Edit. */
function TimingPanel({ store, onSave }: { store: Store; onSave: (patch: StorePatch) => void }) {
  const t = useT()
  const [availabilityReminderDay, setAvailabilityReminderDay] = useState(store.availabilityReminderDay)
  const [availabilityReminderTime, setAvailabilityReminderTime] = useState(store.availabilityReminderTime)
  const [autoGenerateDay, setAutoGenerateDay] = useState(store.autoGenerateDay)
  const [autoGenerateTime, setAutoGenerateTime] = useState(store.autoGenerateTime)

  const select = 'rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-xs text-ink outline-none'
  const fieldLabel = 'flex flex-wrap items-center gap-1.5 font-body text-[11px] font-bold text-muted-ink'
  const timeSelect = (value: string, onChange: (v: string) => void) => (
    <select value={value} onChange={(e) => onChange(e.target.value)} className={select}>
      {TIME_OPTIONS.map((tm) => (
        <option key={tm} value={tm}>
          {to12(tm)}
        </option>
      ))}
    </select>
  )
  const daySelect = (value: DayOfWeek, onChange: (v: DayOfWeek) => void) => (
    <select value={value} onChange={(e) => onChange(e.target.value as DayOfWeek)} className={select}>
      {DAYS.map((d) => (
        <option key={d} value={d}>
          {t(`closing.day.${d}`)}
        </option>
      ))}
    </select>
  )

  return (
    <div className="mt-2 flex flex-col gap-2 rounded-xl border-2 border-ink/15 bg-cream/40 p-2.5">
      <span className="font-body text-[10px] font-bold uppercase tracking-wide text-muted-ink">
        {t('stores.timing.heading')}
      </span>
      <label className={fieldLabel}>
        {t('stores.timing.availabilityReminder')}
        {daySelect(availabilityReminderDay, setAvailabilityReminderDay)}
        {timeSelect(availabilityReminderTime, setAvailabilityReminderTime)}
      </label>
      <label className={fieldLabel}>
        {t('stores.timing.autoGenerate')}
        {daySelect(autoGenerateDay, setAutoGenerateDay)}
        {timeSelect(autoGenerateTime, setAutoGenerateTime)}
      </label>
      <span className="font-body text-[10px] text-muted-ink">{t('stores.timing.hint')}</span>
      <button
        onClick={() =>
          onSave({ name: store.name, availabilityReminderDay, availabilityReminderTime, autoGenerateDay, autoGenerateTime })
        }
        className="self-start rounded-full border-2 border-ink bg-green px-3 py-0.5 font-heading text-[11px] font-bold text-white"
      >
        {t('common.save')}
      </button>
    </div>
  )
}

function OrgNameEditor({
  org,
  onSaved,
}: {
  org: { id: number; name: string }
  onSaved: (org: { id: number; name: string }) => void
}) {
  const t = useT()
  const [editing, setEditing] = useState(false)
  const [name, setName] = useState(org.name)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)

  async function save() {
    if (!name.trim() || name.trim() === org.name) {
      setEditing(false)
      return
    }
    setBusy(true)
    setError(null)
    try {
      onSaved(await api.updateOrgName(name.trim()))
      setEditing(false)
    } catch (e) {
      setError(e instanceof Error ? e.message : t('stores.errRenameOrg'))
    } finally {
      setBusy(false)
    }
  }

  if (!editing) {
    return (
      <div className="flex items-center gap-2">
        <span className="font-heading text-base font-extrabold text-ink">{org.name}</span>
        <button
          onClick={() => {
            setName(org.name)
            setEditing(true)
          }}
          className="font-body text-[11px] font-bold text-muted-ink underline"
        >
          {t('stores.rename')}
        </button>
      </div>
    )
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <input
        autoFocus
        value={name}
        onChange={(e) => setName(e.target.value)}
        onKeyDown={(e) => e.key === 'Enter' && void save()}
        className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-sm text-ink outline-none"
      />
      <button
        disabled={busy || !name.trim()}
        onClick={() => void save()}
        className="rounded-full border-2 border-ink bg-green px-3 py-0.5 font-heading text-[11px] font-bold text-white disabled:opacity-50"
      >
        {t('common.save')}
      </button>
      <button
        onClick={() => setEditing(false)}
        className="rounded-full border-2 border-ink bg-cream px-3 py-0.5 font-heading text-[11px] font-bold text-ink"
      >
        {t('stores.cancel')}
      </button>
      {error && <p className="w-full font-body text-xs font-bold text-coral-dark">{error}</p>}
    </div>
  )
}

function PayCycleEditor({
  org,
  onSaved,
}: {
  org: { id: number; name: string; payPeriodType: PayPeriodType; payPeriodAnchor: string }
  onSaved: (org: { id: number; name: string; payPeriodType: PayPeriodType; payPeriodAnchor: string }) => void
}) {
  const t = useT()
  const [editing, setEditing] = useState(false)
  const [type, setType] = useState<PayPeriodType>(org.payPeriodType)
  const [anchor, setAnchor] = useState(org.payPeriodAnchor)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function save() {
    setBusy(true)
    setError(null)
    try {
      const updated = await api.updatePayPeriod({
        payPeriodType: type,
        ...(type === 'BIWEEKLY' ? { payPeriodAnchor: anchor } : {}),
      })
      onSaved({ ...org, ...updated })
      setEditing(false)
    } catch (e) {
      setError(e instanceof Error ? e.message : t('stores.errPayPeriod'))
    } finally {
      setBusy(false)
    }
  }

  if (!editing) {
    return (
      <div className="flex items-center gap-2">
        <span className="font-body text-xs text-muted-ink">
          {t('stores.payPeriod.current', { type: t(`payPeriod.type.${org.payPeriodType}`) })}
        </span>
        <button
          onClick={() => {
            setType(org.payPeriodType)
            setAnchor(org.payPeriodAnchor)
            setEditing(true)
          }}
          className="font-body text-[11px] font-bold text-muted-ink underline"
        >
          {t('stores.payPeriod.edit')}
        </button>
      </div>
    )
  }

  return (
    <div className="flex flex-wrap items-center gap-2 rounded-xl border-2 border-ink/15 bg-cream/60 p-2">
      <select
        value={type}
        onChange={(e) => setType(e.target.value as PayPeriodType)}
        className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-xs text-ink outline-none"
      >
        <option value="WEEKLY">{t('payPeriod.type.WEEKLY')}</option>
        <option value="BIWEEKLY">{t('payPeriod.type.BIWEEKLY')}</option>
        <option value="MONTHLY">{t('payPeriod.type.MONTHLY')}</option>
      </select>
      {type === 'BIWEEKLY' && (
        <label className="flex items-center gap-1.5 font-body text-[10px] font-bold text-muted-ink">
          {t('stores.payPeriod.anchor')}
          <input
            type="date"
            value={anchor}
            onChange={(e) => setAnchor(e.target.value)}
            className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-xs text-ink outline-none"
          />
        </label>
      )}
      <button
        disabled={busy}
        onClick={() => void save()}
        className="rounded-full border-2 border-ink bg-green px-3 py-0.5 font-heading text-[11px] font-bold text-white disabled:opacity-50"
      >
        {t('common.save')}
      </button>
      <button
        onClick={() => setEditing(false)}
        className="rounded-full border-2 border-ink bg-cream px-3 py-0.5 font-heading text-[11px] font-bold text-ink"
      >
        {t('stores.cancel')}
      </button>
      {error && <p className="w-full font-body text-xs font-bold text-coral-dark">{error}</p>}
    </div>
  )
}

const checkboxRow =
  'flex items-center gap-1.5 font-body text-[11px] font-bold text-muted-ink'

function AddStore({ onAdd, startOpen = false }: { onAdd: (patch: StorePatch) => void; startOpen?: boolean }) {
  const t = useT()
  const [open, setOpen] = useState(startOpen)
  const [name, setName] = useState('')
  const [requiresOpenerSkill, setRequiresOpenerSkill] = useState(true)
  const [pairNewWorkers, setPairNewWorkers] = useState(false)

  function submit(e: FormEvent) {
    e.preventDefault()
    if (!name.trim()) return
    onAdd({ name: name.trim(), requiresOpenerSkill, pairNewWorkers })
    setName('')
    setRequiresOpenerSkill(true)
    setPairNewWorkers(false)
    setOpen(false)
  }

  // adding a store is rare — keep the form out of the way until asked for
  if (!open) {
    return (
      <button
        onClick={() => setOpen(true)}
        className="mb-3 rounded-full border-2 border-dashed border-ink/40 px-3 py-1 font-heading text-xs font-bold text-muted-ink hover:border-ink hover:text-ink"
      >
        + {t('stores.addStore')}
      </button>
    )
  }

  return (
    <form
      onSubmit={submit}
      className="mb-3 flex flex-wrap items-center gap-x-3 gap-y-2 rounded-2xl border-[2.5px] border-ink bg-paper p-3 shadow-[3px_3px_0_var(--color-ink)]"
    >
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder={t('stores.newStoreNamePlaceholder')}
        className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-xs text-ink outline-none"
      />
      <label className={checkboxRow}>
        <input
          type="checkbox"
          checked={requiresOpenerSkill}
          onChange={(e) => setRequiresOpenerSkill(e.target.checked)}
        />
        {t('stores.openerSkillLabel')}
      </label>
      <label className={checkboxRow}>
        <input
          type="checkbox"
          checked={pairNewWorkers}
          onChange={(e) => setPairNewWorkers(e.target.checked)}
        />
        {t('stores.pairNewWorkersLabel')}
      </label>
      <Button type="submit" disabled={!name.trim()}>
        {t('stores.addStore')}
      </Button>
      <button
        type="button"
        onClick={() => setOpen(false)}
        className="font-body text-[11px] font-bold text-muted-ink underline"
      >
        {t('stores.cancel')}
      </button>
    </form>
  )
}

function AddSection({ onAdd, onCancel }: { onAdd: (name: string) => void; onCancel: () => void }) {
  const t = useT()
  const [name, setName] = useState('')

  function submit(e: FormEvent) {
    e.preventDefault()
    if (!name.trim()) return
    onAdd(name.trim())
  }

  return (
    <form
      onSubmit={submit}
      className="flex flex-wrap items-center gap-2 rounded-2xl border-[2.5px] border-dashed border-ink/40 bg-paper p-2.5"
    >
      <input
        autoFocus
        value={name}
        onChange={(e) => setName(e.target.value)}
        placeholder={t('stores.newSectionNamePlaceholder')}
        className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-xs text-ink outline-none"
      />
      <Button type="submit" size="sm" disabled={!name.trim()}>
        {t('stores.addSection')}
      </Button>
      <button
        type="button"
        onClick={onCancel}
        className="rounded-full border-2 border-ink bg-cream px-3 py-0.5 font-heading text-[11px] font-bold text-ink"
      >
        {t('stores.cancel')}
      </button>
    </form>
  )
}

function EditStore({
  store,
  hasSections = false,
  onSave,
  onCancel,
}: {
  store: Store
  /** true once this store has its own sections — the opener/pairing/closing-
   * duties settings never apply to a store that's never itself scheduled,
   * so don't offer to edit them */
  hasSections?: boolean
  onSave: (patch: StorePatch) => void
  onCancel: () => void
}) {
  const t = useT()
  const [name, setName] = useState(store.name)
  const [requiresOpenerSkill, setRequiresOpenerSkill] = useState(store.requiresOpenerSkill)
  const [pairNewWorkers, setPairNewWorkers] = useState(store.pairNewWorkers)
  const [tracksClosingDuties, setTracksClosingDuties] = useState(store.tracksClosingDuties)

  return (
    <div className="flex flex-col gap-3 rounded-2xl border-[2.5px] border-ink bg-paper p-3 shadow-[3px_3px_0_var(--color-ink)]">
      <input
        value={name}
        onChange={(e) => setName(e.target.value)}
        className="rounded-lg border-2 border-ink bg-cream px-2 py-1 font-body text-sm font-bold text-ink outline-none"
      />
      {!hasSections && (
        <div className="flex flex-wrap gap-x-3 gap-y-1.5">
          <label className={checkboxRow}>
            <input
              type="checkbox"
              checked={requiresOpenerSkill}
              onChange={(e) => setRequiresOpenerSkill(e.target.checked)}
            />
            {t('stores.openerSkillRequiredLabel')}
          </label>
          <label className={checkboxRow}>
            <input
              type="checkbox"
              checked={pairNewWorkers}
              onChange={(e) => setPairNewWorkers(e.target.checked)}
            />
            {t('stores.pairNewWorkersLabel')}
          </label>
          <label className={checkboxRow}>
            <input
              type="checkbox"
              checked={tracksClosingDuties}
              onChange={(e) => setTracksClosingDuties(e.target.checked)}
            />
            {t('stores.tracksClosingDutiesLabel')}
          </label>
        </div>
      )}
      <div className="flex justify-end gap-2 border-t border-ink/10 pt-2.5">
        <button
          onClick={() =>
            name.trim() &&
            onSave({
              name: name.trim(),
              requiresOpenerSkill,
              pairNewWorkers,
              tracksClosingDuties,
            })
          }
          className="rounded-full border-2 border-ink bg-green px-3 py-0.5 font-heading text-[11px] font-bold text-white"
        >
          {t('common.save')}
        </button>
        <button
          onClick={onCancel}
          className="rounded-full border-2 border-ink bg-cream px-3 py-0.5 font-heading text-[11px] font-bold text-ink"
        >
          {t('stores.cancel')}
        </button>
      </div>
    </div>
  )
}
