-- Per-store timing for the weekly "check your availability" reminder email
-- and next-week draft auto-generation, replacing what was previously one
-- fixed, platform-wide schedule (Fri 12:00 / Sat 08:00 server time).
ALTER TABLE "Store" ADD COLUMN "availabilityReminderDay" "DayOfWeek" NOT NULL DEFAULT 'FRIDAY';
ALTER TABLE "Store" ADD COLUMN "availabilityReminderTime" TEXT NOT NULL DEFAULT '12:00';
ALTER TABLE "Store" ADD COLUMN "autoGenerateDay" "DayOfWeek" NOT NULL DEFAULT 'SATURDAY';
ALTER TABLE "Store" ADD COLUMN "autoGenerateTime" TEXT NOT NULL DEFAULT '08:00';
